### ISSUE TITLE
Test: indexing of special values

### ISSUE THREAD

**Issue by samalloing** [libis/ca_crkc#14]
To help test #4  you can check if special fields are indexed properly:
* daterange fields should be indexed properly. The date should get accepted by Solr. The test should call the functions to process a date and the output XML that is send to solr should contain a valid solr date format.
* Also the special fields like type_id should be properly formatted (the indexed string is the same as the searched string)
* Values in containers should be indexed

**Comment by naeemmuhammad** [comment]
1. beeld (vrijstaand) => beeld vrijstaand (characters '(' and ')' are removed while indexing, therefore should be searched without these characters)
2. beeld, vrijstaand => beeld vrijstaand (character ',' is removed while indexing therefore should be searched without it)

3. beeld-vrijstaand => beeld-vrijstaand   (character '-' is included while indexing therefore should be part of the search keywords)
4. beeld_vrijstaand => beeld_vrijstaand  (character '_' is included while indexing therefore should be part of the search keywords)

**Comment by roxannewyns** [comment]
Works:
reliëf ; belgië
vlaams-brabant

Doesn't work:
procédé: both search on 'procédé' and 'procede'
materiaal -en techniek: both on 'materiaal -en techniek' and 'materiaal en techniek'
brabant, leuven: gives result when searching on 'brabant, leuven ', so with a space behind. But 'brabant, leuven' and 'brabant leuven' don't work

In general I don't find it logical that one time you can't use the special characters e.g. 'beeld (vrijstaand)' and the other time you have to 'brabant, leuven'. 

For the user this is trial and error depending on the character. What's the logic behind it? Please describe. 
Can't the rule always be the same?

**Comment by naeemmuhammad** [comment]
Some updates:
Collective Access removes certain special characters while indexing (as in my previous post) whereas some special characters are indexed. For those special characters that are removed while indexing, Collective Access does not remove them while they are used in a search term. 
I implemented a fix that removes special character while we make search, that solves the problem for ('(', ')' and ','). However this fix fails in certain cases, for example while indexing and searching time stamps, therefore we need another fix. Because Collective Access does not tackle each special character in the same way, removing special character from the search does not seem to be an option. 

Status:
We have decided not to peruse this issue until we decide otherwise later on.
