### ISSUE TITLE
URLs in the advanced search form don't work

### ISSUE THREAD

**Issue by samalloing** [libis/ca_crkc#32]
In URL fields in the advanced search get extra '{}' added. If you search you, you don't get a result.

cc @roxannewyns

**Comment by roxannewyns** [comment]
@ Naeem: a small issue to pick up. Can you check if this is solver in 1.6? If not, perhaps file a jiyra for it to see if CollectiveAccess will do something about it.

**Comment by naeemmuhammad** [comment]
URL search works correctly in version 1.6. However, in order to make the complete url searchable url field should be used without tokenization. Corresponding question on Collective Access forum:
http://www.collectiveaccess.org/support/forum/index.php?p=/discussion/295281/url-field-based-search#latest)
