### ISSUE TITLE
Auto Logout 

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/ca_crkc#33]
CA logouts automatically while performing various operations, such as saving and browsing.

**Comment by roxannewyns** [comment]
This mostly happens when you open multiple tabs at the same time (e.g. opening records from your search results in different windows, working in multiple records at the same time). If you don't wait until  the page is fully loaded, the system logs out and you get the log-in screen. Advice to partner not to open multiple tabs or at least wait until everything is loaded. This already helps but even with one page a single action can sometimes give a log-out. To be explored why this happens.

**Comment by roxannewyns** [comment]
Ik heb hier al lang geen meldingen meer over gekregen, dus sluit dit.
